In [1]:
# question 1

import numpy as np

np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [2]:
# question 2

import numpy as np
list1=[]
list2=[]
for i in range(5):
    x=int(input("enter the values for list1: "))
    list1.append(x)
for i in range(5):
    x=int(input("enter the value for list2: "))
    list2.append(x)
arr1=np.array(list1)
arr2=np.array(list2)
arr=np.concatenate((arr1,arr2))
print("concatenated array:",arr)
sortArr=np.sort(arr)
print("sorted array:",sortArr)

enter the values for list1: 23
enter the values for list1: 21
enter the values for list1: 3
enter the values for list1: 6
enter the values for list1: 34
enter the value for list2: 5
enter the value for list2: 78
enter the value for list2: 43
enter the value for list2: 1
enter the value for list2: 98
concatenated array: [23 21  3  6 34  5 78 43  1 98]
sorted array: [ 1  3  5  6 21 23 34 43 78 98]


In [ ]:
# question 3

arr=np.array([[1,2,3],[4,5,6]])
print("dimensions in array:",arr.ndim)
print("size of array:",arr.size)

In [4]:
# question 4 (np.newaxis)

import numpy as np
arr=np.arange(15)
print("shape of array:",arr.shape)
rowarr=arr[np.newaxis,:]
print("shape of 2d array in row:",rowarr.shape)
colarr=arr[:,np.newaxis]
print("shape of 2d array in col:",colarr.shape)



shape of array: (15,)
shape of 2d array in row: (1, 15)
shape of 2d array in col: (15, 1)


In [9]:
# question 4 (np.expand_dims)

import numpy as np
arr=np.arange(15)
print("shape of array:",arr.shape)
rowarr=np.expand_dims(arr,axis=0)
print("shape of 2d array in row:",rowarr.shape)
colarr=np.expand_dims(arr,axis=1)
print("shape of 2d array in col:",colarr.shape)


shape of array: (15,)
shape of 2d array in row: (1, 15)
shape of 2d array in col: (15, 1)


In [6]:
# question 5  (np.hstack, np.vstack)

import numpy as np
arr1=np.square([1,2,3,4,5])
arr2=np.square([6,7,8,9,10])
print("horizontal append:",np.hstack((arr1,arr2)))
print("vertical append:",np.vstack((arr1,arr2)))


horizontal append: [  1   4   9  16  25  36  49  64  81 100]
vertical append: [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [10]:
# question 6 

import numpy as np
arr1=np.array([4,1,15,9,1,4,2,3,2,5,6,3,6,9])
unique,counts=np.unique(arr1,return_counts=True)
arr=np.asarray((unique,counts)).T
print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  2]
 [ 4  2]
 [ 5  1]
 [ 6  2]
 [ 9  2]
 [15  1]]
